### ISSUE TITLE
TypeError: Cannot read property '_buffer' of undefined

### ISSUE THREAD

**Issue by ralphholzmann** [LaurentZuijdwijk/streaming-cache#15]
I've dropped this module into my app as a way to retry streaming file uploads if they should fail or be throttled. It works really well, but every so often the app crashes with this error:

```
TypeError: Cannot read property '_buffer' of undefined
    at Duplex.<anonymous> (streaming-cache/index.js:191:59)
```

Somehow, it's getting into a state where the `cache` has a hit, but the associated `emitters` dictionary does not, causing this error.

I'm going to investigate further and see if I can figure out how this is happening. Documenting it here for now.

**Comment by LaurentZuijdwijk** [comment]
Thank you @ralphholzmann. Please let me know if I can assist you with this.

**Comment by jotto** [comment]
I've been working through these bugs with this branch here: https://github.com/jotto/streaming-cache/commits/concurrent-requests-stall (the branch name is a reference to the first commit, but not the recent commits)

I created another issue here: https://github.com/LaurentZuijdwijk/streaming-cache/issues/16, but it may be the same bug.

I'm guessing it's due to stream being aborted by client.

**Comment by LaurentZuijdwijk** [comment]
You guys happy for me to close this issue?

**Comment by jotto** [comment]
👍
